subsystem:
    hbmqtt:
        enable: true
        process: true
        config:
            listeners:
                default:
                    max-connections: 50000
                    type: 'tcp'
                local:
                    bind: '127.0.0.1:1883'
            timeout-disconnect-delay: 2
            auth:
                plugins: ['auth.anonymous']
                allow-anonymous: true

    mqttbridge:
        enable: false
        process: false
        config:
            brokers:
                local:
                    protocol: 'mqtt'
                    host: 'localhost'
                single:
                    protocol: 'mqtt'
                    host: 'm23.cloudmqtt.com'
                    port: 11702
                    username: 'oleffxza'
                    password: '8ViMtnkje343'
                    topics: [
                        ['light/1', 0], 
                        ['another', 0]
                    ]

    plugins:
        enable: true
        process: true
        config:
            plugins_dir: 'plugindir'
            plugin_poll_interval: 20

    http:
        enable: true
        process: false
        config:
            addr: 'localhost'
            port: 8080

# logging configuration
asyncio:
    debug: true

logging:
    basicConfig:
        level: 'DEBUG'
        #format: '%(asctime)s [%(levelname)s] %(module)s:%(lineno)d: %(message)s'
    packages:
        asyncio: 'WARNING'
        asyncio.poll: 'WARNING'
        transitions: 'WARNING'
        athome.subsystem.mqttbridge: 'DEBUG'
        athome.subsystem.plugins: 'DEBUG'
        hbmqtt: 'WARNING'


