subsystem:
    hbmqtt:
        enable: false
        config:
            listeners:
                default:
                    max-connections: 50000
                    type: 'tcp'
                local:
                    bind: '127.0.0.1:1883'
            timeout-disconnect-delay: 2
            auth:
                plugins: ['auth.anonymous']
                allow-anonymous: true

    mqttbridge:
        enable: false
        config:
            brokers:
                local:
                    enable: true
                    protocol: 'mqtt'
                    host: 'localhost'
                    topics: [
                        ['another', 1]
                    ]
                single:
                    enable: false
                    protocol: 'mqtt'
                    host: 'm23.cloudmqtt.com'
                    port: 11702
                    username: 'oleffxza'
                    password: '8ViMtnkje343'
                    topics: [
                        ['light/1', 0], 
                    ['another', 0]
                ]

    plugins:
        enable: true
        config:
            plugins_dir: 'plugindir'
            plugin_poll_interval: 5

    http:
        enable: false
        process: false
        config:
            addr: 'localhost'
            port: 8080

# logging configuration
asyncio:
    debug: true

logging:
    version: 1
    disable_existing_loggers: true

    root:
        level: 'DEBUG'
        handlers: ['console_handler']
        formatter: 'standard'
        
    formatters:
        standard:
            format: "%(levelname)s %(asctime)s [%(name)s]  %(message)s"

    handlers:
        console_handler:
            class: 'logging.StreamHandler'
            level: 'DEBUG'
            formatter: 'standard'
            stream: 'ext://sys.stdout'

        syslog_handler:
            class: 'logging.handlers.SysLogHandler'
            level: 'INFO'
            formatter: 'standard'

    loggers: 
        asyncio:
            level: 'DEBUG'
            handlers: [ 'console_handler']
        transitions:
            level: 'WARNING'
            handlers: ['console_handler']
        athome.subsystem.mqttbridge:
            level: 'DEBUG'
            handlers: ['console_handler']
        athome.subsystem.plugins:
            level: 'DEBUG'
            handlers: ['console_handler']
        hbmqtt: 
            level: 'DEBUG'
            handlers: ['console_handler']


