core: 

    config_poll_interval: 5


subsystem:
           
    hbmqtt:
        enable: true
        config:
            listeners:
                default:
                    max-connections: 50000
                    type: tcp
                local:
                    bind: 127.0.0.1:1883
            timeout-disconnect-delay: 2
            auth:
                plugins: ['auth.anonymous']
                allow-anonymous: true

    mqttbridge:
        enable: false
        config:
            brokers:
                local:
                    protocol: 'mqtt'
                    host: 'localhost'
                single:
                    protocol: 'mqtt'
                    host: 'm23.cloudmqtt.com'
                    port: 11702
                    username: 'oleffxza'
                    password: '8ViMtnkje343'
            topics: [
                        ['light/1', 0], 
                        ['another', 0]
                    ]
 
    plugins:
        enable: false
        config:
            plugins_dir: 'plugindir'
            plugin_poll_interval: 5
