env:
    tmp_dir: 'auto'
    run_dir: 'auto'

subsystem:
    hbmqtt:
        enable: false
        class: 'athome.subsystems.hbmqtt.Subsystem'
        config:
            listeners:
                default:
                    max-connections: 50000
                    type: 'tcp'
                local:
                    bind: '127.0.0.1:1883'
            timeout-disconnect-delay: 2
            auth:
                plugins: ['auth.anonymous']
                allow-anonymous: true

    mqttbridge:
        enable: true
        class: 'athome.subsystems.mqttbridge.Subsystem'
        config:
            brokers:
                local:
                    enable: true
                    protocol: 'mqtt'
                    host: 'localhost'
                    topics: [
                        ['extern/tv/0/mute', 1], 
                        ['extern/tv/0/volume', 1]
                    ]
                extern:
                    enable: true
                    protocol: 'mqtt'
                    host: 'm23.cloudmqtt.com'
                    port: 11702
                    username: 'oleffxza'
                    password: '8ViMtnkje343'
                    topics: [
                        ['tv/0/mute/set', 1], 
                        ['tv/0/volume/set', 1]
                    ]

    tasks:
        enable: true
        class: 'athome.subsystems.tasks.Subsystem'
        config:
            tasks_dir: 'c:/Users/duca/athome-tasks/src'
            poll_interval: 10

    http:
        enable: false
        class: 'athome.subsystems.http.Subsystem'
        config:
            addr: 'localhost'
            port: 8080

# logging configuration
asyncio:
    debug: true

logging:
    version: 1
    disable_existing_loggers: true

    root:
        level: 'DEBUG'
        handlers: ['console_handler']
        formatter: 'standard'
        
    formatters:
        standard:
            format: "%(name)s %(asctime)s [%(levelname)s] %(message)s"

    handlers:
        console_handler:
            class: 'logging.StreamHandler'
            level: 'DEBUG'
            formatter: 'standard'
            stream: 'ext://sys.stdout'

        syslog_handler:
            class: 'logging.handlers.SysLogHandler'
            level: 'INFO'
            formatter: 'standard'

    loggers: 
        asyncio:
            level: 'DEBUG'
            handlers: [ 'console_handler']
        transitions:
            level: 'WARNING'
            handlers: ['console_handler']
        athome.subsystem.mqttbridge:
            level: 'DEBUG'
            handlers: ['console_handler']
        athome.subsystem.plugins:
            level: 'DEBUG'
            handlers: ['console_handler']
        hbmqtt: 
            level: 'WARNING'
            handlers: ['console_handler']


